version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    command: gunicorn -w 4 -b 0.0.0.0:5000 app.main:app
